name: dcd_flut_alarm_manager
description: This repository contains a Flutter mobile application developed for learning fundamental flutter development based on Dicoding Class. The application focuses on creating simple background process with alarm manager on Android.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  android_alarm_manager_plus: ^3.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
